language: node_js
node_js:
  - node

matrix:
  include:

    - os: linux
      sudo: false
      dist: trusty
      addons:
        apt:
          packages:
            - libsecret-1-0
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3

    - os: osx

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

notifications:
  email:
    on_success: change
    on_failure: change
